---
title: "Generated figures"
format: pdf
knitr:
  opts_chunk: 
    out.width: "70%"
    fig.width: 6
    fig.asp: 0.618
    fig.align: "center"
execute: 
  cache: false
  echo: false
---

```{r}
#| label: setup
#| include: false
#| cache: false

library(targets)
source(here::here("scripts/import_dependencies.R"))
devtools::load_all(here::here())

library(ggraph)
```

Loaded pipeline project: `r tar_get_current_project()`

{{< include /../../quarto/fig_popvar_methods.qmd >}}

{{< include /../../quarto/fig_components.qmd >}}

{{< include /../../quarto/fig_across_hab.qmd >}}

{{< include /../../quarto/fig_all_sems.qmd >}}

## Supplementary information

{{< include /../../quarto/sup_maps.qmd >}}

{{< include /../../quarto/suptbl-stats1-selection.qmd >}}

{{< include /../../quarto/sup_stats1_estimates.qmd >}}

```{r}

out_glm <- targets::tar_read(
  models_stab_across_habitats,
  store = store_in_pipeline()
)

data <- targets::tar_read(
  population_variability_data,
  store = store_in_pipeline()
)
```

{{< include /../../quarto/suptbl-stats1-autocor.qmd >}}

{{< include /../../quarto/supfig-stats1-est-spatial.qmd >}}

{{< include /../../quarto/supfig_stats1b_estimates.qmd >}}

{{< include /../../quarto/supfig_sem_buffers.qmd >}}

```{r}
rm(out_glm)
rm(data)
```

{{< include /../../quarto/supfig_montecarlo_trend.qmd >}}

{{< include /../../quarto/supfig_montecarlo_stats1.qmd >}}

{{< include /../../quarto/supfig_montecarlo_sem.qmd >}}

{{< include /../../quarto/supfig_montecarlo_chisq.qmd >}}
