
```{r prepare-supfig-montecarlo-methods}
font_size = 12
set.seed(1803) # the time
trends <- tar_read(
    all_local_trends_outputs,
    store = store_in_pipeline()
) %>% filter(str_detect(series_id, "010511_farmland|390134_woodland"), str_detect(series_id, "PHYCOL|CORCOR|PARMAJ")) %>% 
    split_series_id %>% 
    mutate(
        lwr = qnorm(0.025, mean = trend, sd = se),
        upr = qnorm(0.975, mean = trend, sd = se)
    ) %>% 
    group_by(series_id, lwr, upr, trend, SPECIES, COMMUNITY_ID) %>% 
    reframe(
        draw = rnorm(n(), mean = trend, sd = se)
    ) %>% 
    ungroup

plot_resampling <- trends %>% 
    mutate(
        alpha_right = ifelse(draw > trend, 1, 0),
        alpha_left = ifelse(draw < trend, 1, 0)
    ) %>% 
    ggplot(aes(y = SPECIES)) +
    geom_vline(aes(xintercept = 0), color = "darkgray", linetype = "dashed") +
    # curvature is not mappable as an aesthetic, but we need to change its value based
    # on the direction of the arrow : two geom_curves, one for each direction
    geom_curve( # arrows to the right
        aes(x = trend, xend = draw, yend = SPECIES, color = COMMUNITY_ID, alpha = alpha_right),
        position = position_nudge(y = 0.15),
        curvature = -0.4,
        arrow = arrow(length = unit(0.1, "cm"), type = "closed")
    ) +
    geom_curve( # arrows to the left
        aes(x = trend, xend = draw, yend = SPECIES, color = COMMUNITY_ID, alpha = alpha_left),
        position = position_nudge(y = 0.15),
        curvature = 0.4,
        arrow = arrow(length = unit(0.1, "cm"), type = "closed")
    ) +
    geom_pointrange(aes(xmin = lwr, xmax = upr, x = trend)) +
    geom_point(aes(x = draw, color = COMMUNITY_ID), size = 2) +
    geom_hline(aes(yintercept = -Inf), linewidth = 1.5) +
    scale_alpha_identity() +
    facet_wrap(~COMMUNITY_ID, ncol = 1, scales = "fixed", labeller = labeller(
        COMMUNITY_ID = c(`010511_farmland` = "Community i", `390134_woodland` = "Community j")
    )) +
    cowplot::theme_cowplot(font_size = font_size) +
    scale_color_viridis_d(begin = 0.3, end = 0.9) +
    theme(
        axis.text.y = element_blank(),
        strip.background = element_blank(),
        axis.line.x = element_blank(),
        legend.position = "none"
    ) +
    labs(
        x = "Trend",
        y = "Species"
    )

plot_two_meanabstrend <- trends  %>%
    group_by(COMMUNITY_ID)  %>%
    summarise(
        mean_abs_trend = mean(abs(trend)),
        mean_abs_draw = mean(abs(draw))
    ) %>%
    mutate(
        com_id = factor(c("i", "j"), levels = c("j", "i"))
    ) %>% 
    ggplot(aes(x = mean_abs_draw, y = com_id, color = COMMUNITY_ID)) +
    geom_point(size = 3) +
    scale_color_viridis_d(begin = 0.3, end = 0.9) +
    cowplot::theme_cowplot(font_size = font_size) +
    theme(
        legend.position = "none"
    ) +
    xlim(c(0,0.09)) +
    labs(
        y = "Community",
        x = "Resampled\n mean absolute trend"
    )

resamples <- tar_read(
    mc_meanabstrend_samples,
    store = store_in_pipeline()
) %>% 
    filter(rep_id == 1)

popvar_data <- tar_read(
    population_variability_data,
    store = store_in_pipeline()
)

set.seed(1828)
resamples_subset <- resamples %>% 
    slice_sample(n = 40) 
    
plot_single_model <- resamples_subset %>% 
    left_join(popvar_data, by = "COMMUNITY_ID") %>% 
    ggplot(aes(y = mean_abs_trend_mc, x = mu_SR, color = COMMUNITY_ID)) +
    geom_point(size = 2) +
    geom_smooth(aes(y = mean_abs_trend_mc), color = "darkgray", method = "lm") +
    scale_y_log10() +
    scale_color_viridis_d(begin = 0.3, end = 0.9) +
    cowplot::theme_cowplot(font_size = font_size) +
    theme(
        # axis.text.x = element_blank(),
        legend.position = "none"
    ) +
    labs(
        x = "Explanatory variable",
        y = "Resampled\n mean absolute trend"
    )

plot_est <- tar_read(
    mc_sem_estimates,
    store = store_in_pipeline()
) %>%
    filter(Response == "ata_log", Predictor == "mu_SR" & HABITAT == "farmland") %>% 
    mutate(
        lwr = qnorm(0.025, Estimate, Std.Error),
        upr = qnorm(0.975, Estimate, Std.Error)
    ) %>% 
    filter(rep_id <= 25) %>% 
    ggplot(aes(y = rep_id)) +
    geom_pointrange(aes(xmin = lwr, xmax= upr, x = Estimate), color = "darkgray", size = 0.25)+
    cowplot::theme_cowplot(font_size = font_size) +
    labs(
        x = "Estimate for\n the ecological model",
        y = "MC replicate"
    )


```


```{r build-supfig-montecarlo-methods}
#| fig-asp: 0.9
#| out-width: "80%"
#| out-fig: 8
#| cache: false
cowplot::plot_grid(
    plot_resampling,
    plot_two_meanabstrend,
    plot_single_model,
    plot_est,
    ncol = 2,
    rel_widths = c(1,0.75,1,0.75),
    align = "hv",
    axis = "ltbr",
    labels = c("(a)", "(b)", "(c)", "(d)")
)
```