name: Remote SSH pull
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote git pull via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HPC_HOST }}
          username: ${{ secrets.HPC_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.HPC_USER }}/${{ secrets.HPC_PATH }}
            git checkout main
            git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/birdpopvar.git main
            git status
