name: Remote SSH pull
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote git pull via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HPC_HOST }}
          username: ${{ secrets.HPC_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: ls /home/${{ secrets.HPC_USER }}
